[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "0.0.1"
version_scheme = "semver"
version = "1.0.0"
update_changelog_on_bump = true
major_version_zero = true
version_files = ["meson.build:version"]
