name: Build and Test Code
run-name: ${{ gitea.ref }} Build
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: gitea.shrukanslab.xyz/sl-devs/cpp-template/dev-environment:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Unit test
        run: just test

      - name: Compress test report
        run: tar -czf build/test_logs.tar.gz build/meson-logs

      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: test_logs
          path: build/test_logs.tar.gz
          retention-days: 5

  coverage:
    runs-on: ubuntu-latest
    container: gitea.shrukanslab.xyz/sl-devs/cpp-template/dev-environment:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Coverage
        run: just coverage

      - name: Compress coverage report
        run: tar -czf build/coverage.tar.gz build/meson-logs/coveragereport

      - name: Archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: build/coverage.tar.gz
          retention-days: 5

  static_analysis:
    runs-on: ubuntu-latest
    container: gitea.shrukanslab.xyz/sl-devs/cpp-template/dev-environment:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure
        run: just configure

      - name: Static analysis
        run: just check

  sanitize:
    runs-on: ubuntu-latest
    container: gitea.shrukanslab.xyz/sl-devs/cpp-template/dev-environment:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure
        run: just configure

      - name: Sanitize
        run: just sanitize
