name: Build and Test Code
run-name: ${{ gitea.ref }} Build
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: gitea.shrukanslab.xyz/cpp-template/dev-environment:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Unit test
        run: just test

  coverage:
    runs-on: ubuntu-latest
    container: gitea.shrukanslab.xyz/cpp-template/dev-environment:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Coverage
        run: just coverage

      - name: Compress coverage report
        run: tar -czf build/coverage.tar.gz build/meson-logs/coveragereport

      - name: Archive coverage report
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build/coverage.tar.gz
          retention-days: 5

  static_analysis:
    runs-on: ubuntu-latest
    container: gitea.shrukanslab.xyz/cpp-template/dev-environment:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Static analysis
        run: just check

  sanitize:
    runs-on: ubuntu-latest
    container: gitea.shrukanslab.xyz/cpp-template/dev-environment:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Sanitize
        run: just sanitize
